# Generated by Django 5.2.4 on 2025-10-04 04:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("supplier", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("quantity", models.IntegerField()),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("LOCAL", "Local "),
                            ("BUFFET", "Buffet"),
                            ("DECOR", "Decoração"),
                            ("PHOTO_VIDEO", "Fotografia e Vídeo"),
                            ("ATTIRE", "Vestuário"),
                            ("MUSIC", "Música/Entretenimento"),
                            ("OTHERS", "Outros"),
                        ],
                        default="OTHERS",
                        max_length=20,
                        verbose_name="Categoria",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="supplier.supplier",
                    ),
                ),
            ],
        ),
    ]
