# Generated by Django 5.2.3 on 2025-07-11 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('budget', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True)),
                ('quantidade', models.IntegerField()),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.fornecedor')),
                ('orcamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.orcamento')),
            ],
        ),
    ]
