# Generated by Django 5.2.3 on 2025-07-11 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0001_initial"),
        ("suplier", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="fornecedor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="suplier.fornecedor"
            ),
        ),
    ]
