# Generated by Django 5.2.4 on 2025-08-02 01:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0001_initial"),
        ("supplier", "0001_initial"),
        ("weddings", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="budget",
        ),
        migrations.AddField(
            model_name="item",
            name="wedding",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="weddings.wedding",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="supplier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="supplier.supplier",
            ),
        ),
    ]
