# Generated by Django 5.2.6 on 2025-10-01 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_remove_item_budget_item_wedding_alter_item_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('BUFFET', 'Local e Buffet'), ('DECOR', 'Decoração'), ('PHOTO_VIDEO', 'Fotografia e Vídeo'), ('ATTIRE', 'Vestuário'), ('MUSIC', 'Música/Entretenimento'), ('OTHERS', 'Outros')], default='OTHERS', max_length=20, verbose_name='Categoria'),
        ),
    ]
