# Generated by Django 5.2.4 on 2025-11-08 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pendente"),
                    ("IN_PROGRESS", "Em Andamento"),
                    ("DONE", "Concluído"),
                ],
                default="PENDING",
                max_length=20,
                verbose_name="Status",
            ),
        ),
    ]
