# Generated by Django 5.2.4 on 2025-11-23 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_alter_item_options_alter_item_quantity_and_more'),
        ('items', '0003_alter_item_quantity_alter_item_unit_price'),
    ]

    operations = [
    ]
