# Generated by Django 5.2.4 on 2025-12-07 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_merge_20251123_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='supplier',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Fornecedor'),
            preserve_default=False,
        ),
    ]
