# Generated by Django 5.2.3 on 2025-07-11 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('budget', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_assinatura', models.DateField()),
                ('validade', models.DateField(blank=True, null=True)),
                ('descricao', models.TextField(blank=True)),
                ('status', models.CharField(blank=True, max_length=50)),
                ('cerimonialista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.cerimonialista')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.cliente')),
                ('orcamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.orcamento')),
            ],
        ),
    ]
