# Generated by Django 5.2.4 on 2025-08-02 01:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0001_initial"),
        ("items", "0001_initial"),
        ("weddings", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contract",
            name="budget",
        ),
        migrations.RemoveField(
            model_name="contract",
            name="client",
        ),
        migrations.RemoveField(
            model_name="contract",
            name="planner",
        ),
        migrations.AddField(
            model_name="contract",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="contract",
            name="item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="items.item",
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="wedding",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="weddings.wedding",
            ),
        ),
    ]
