# Generated by Django 5.2.4 on 2025-11-20 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_initial'),
        ('items', '0003_alter_item_quantity_alter_item_unit_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contract',
            options={'verbose_name': 'Contrato', 'verbose_name_plural': 'Contratos'},
        ),
        migrations.AlterField(
            model_name='contract',
            name='description',
            field=models.TextField(blank=True, verbose_name='Descrição/Observações'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='expiration_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Vencimento'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contract', to='items.item', verbose_name='Item'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='signature_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Assinatura'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendente'), ('SIGNED', 'Assinado'), ('COMPLETED', 'Finalizado'), ('CANCELED', 'Cancelado')], default='PENDING', max_length=20, verbose_name='Status'),
        ),
    ]
