# Generated by Django 5.2.4 on 2025-10-21 23:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contracts', '0002_initial'),
        ('weddings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='wedding',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='weddings.wedding'),
        ),
    ]
