# Generated by Django 5.2.4 on 2025-11-12 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0003_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Data e hora em que foi atualizado pela última vez.",
                verbose_name="Última Atualização",
            ),
        ),
        migrations.AlterField(
            model_name="contract",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Data e hora em que este objeto foi criado.",
                verbose_name="Data de Criação",
            ),
        ),
    ]
