# Generated by Django 5.2.4 on 2025-11-21 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0004_alter_contract_options_contract_signature_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contract',
            old_name='signed_at',
            new_name='couple_signed_at',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='expiration_date',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='signature_date',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='signature_image',
        ),
        migrations.AddField(
            model_name='contract',
            name='couple_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='couple_signature',
            field=models.FileField(blank=True, null=True, upload_to='signatures/couple/'),
        ),
        migrations.AddField(
            model_name='contract',
            name='final_pdf',
            field=models.FileField(blank=True, null=True, upload_to='contracts_pdf/'),
        ),
        migrations.AddField(
            model_name='contract',
            name='integrity_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='planner_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='planner_signature',
            field=models.FileField(blank=True, null=True, upload_to='signatures/planner/'),
        ),
        migrations.AddField(
            model_name='contract',
            name='planner_signed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='supplier_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='supplier_signature',
            field=models.FileField(blank=True, null=True, upload_to='signatures/supplier/'),
        ),
        migrations.AddField(
            model_name='contract',
            name='supplier_signed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='description',
            field=models.TextField(blank=True, help_text='Cláusulas específicas ou descrição do serviço.'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Rascunho'), ('WAITING_PLANNER', 'Aguardando Cerimonialista'), ('WAITING_SUPPLIER', 'Aguardando Fornecedor'), ('WAITING_COUPLE', 'Aguardando Noivos'), ('COMPLETED', 'Concluído'), ('CANCELED', 'Cancelado')], default='WAITING_PLANNER', max_length=50),
        ),
    ]
