# Generated by Django 5.2.4 on 2025-11-23 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0005_rename_signed_at_contract_couple_signed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='external_pdf',
            field=models.FileField(blank=True, null=True, upload_to='contracts_external/'),
        ),
    ]
