# Generated by Django 5.2.4 on 2025-12-07 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0006_contract_external_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='couple_signature',
            field=models.FileField(blank=True, null=True, upload_to='signatures/couple/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='external_pdf',
            field=models.FileField(blank=True, null=True, upload_to='contracts_external/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='final_pdf',
            field=models.FileField(blank=True, null=True, upload_to='contracts_pdf/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='integrity_hash',
            field=models.CharField(blank=True, default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contract',
            name='planner_signature',
            field=models.FileField(blank=True, null=True, upload_to='signatures/planner/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='supplier_signature',
            field=models.FileField(blank=True, null=True, upload_to='signatures/supplier/%Y/%m/%d/'),
        ),
    ]
