# Generated by Django 5.2.10 on 2026-02-04 03:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finances', '0001_initial'),
        ('logistics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='contract',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense', to='logistics.contract'),
        ),
        migrations.AddField(
            model_name='installment',
            name='expense',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='finances.expense'),
        ),
        migrations.AlterUniqueTogether(
            name='budgetcategory',
            unique_together={('budget', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='installment',
            unique_together={('expense', 'installment_number')},
        ),
    ]
