# Generated by Django 5.2.10 on 2026-02-16 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finances', '0001_initial'),
        ('logistics', '0001_initial'),
        ('weddings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='wedding',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='budget', to='weddings.wedding', verbose_name='Casamento'),
        ),
        migrations.AddField(
            model_name='budgetcategory',
            name='budget',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='finances.budget', verbose_name='Orçamento Pai'),
        ),
        migrations.AddField(
            model_name='budgetcategory',
            name='wedding',
            field=models.ForeignKey(help_text='Vincula o registro a um evento específico gerenciado pelo Planner.', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='weddings.wedding', verbose_name='Casamento'),
        ),
        migrations.AddField(
            model_name='expense',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='finances.budgetcategory'),
        ),
        migrations.AddField(
            model_name='expense',
            name='contract',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense', to='logistics.contract'),
        ),
        migrations.AddField(
            model_name='expense',
            name='wedding',
            field=models.ForeignKey(help_text='Vincula o registro a um evento específico gerenciado pelo Planner.', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='weddings.wedding', verbose_name='Casamento'),
        ),
        migrations.AddField(
            model_name='installment',
            name='expense',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='finances.expense'),
        ),
        migrations.AddField(
            model_name='installment',
            name='wedding',
            field=models.ForeignKey(help_text='Vincula o registro a um evento específico gerenciado pelo Planner.', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='weddings.wedding', verbose_name='Casamento'),
        ),
        migrations.AlterUniqueTogether(
            name='budgetcategory',
            unique_together={('budget', 'name')},
        ),
        migrations.AddIndex(
            model_name='installment',
            index=models.Index(fields=['status', 'due_date'], name='finances_in_status_988428_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='installment',
            unique_together={('expense', 'installment_number')},
        ),
    ]
