# Generated by Django 5.2.10 on 2026-02-10 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0002_initial'),
        ('weddings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetcategory',
            name='wedding',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weddings.wedding', verbose_name='Casamento'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='wedding',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weddings.wedding', verbose_name='Casamento'),
        ),
        migrations.AlterField(
            model_name='installment',
            name='wedding',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weddings.wedding', verbose_name='Casamento'),
        ),
    ]
