# Generated by Django 5.2.10 on 2026-02-20 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0002_initial'),
        ('weddings', '0002_alter_wedding_managers_remove_wedding_deleted_at_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='budgetcategory',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='budgetcategory',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='budgetcategory',
            name='is_deleted',
        ),
        migrations.AlterField(
            model_name='budgetcategory',
            name='wedding',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='weddings.wedding'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='wedding',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='weddings.wedding'),
        ),
        migrations.AlterField(
            model_name='installment',
            name='wedding',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='weddings.wedding'),
        ),
    ]
