# Generated by Django 5.2.10 on 2026-05-04 23:41

from django.db import migrations, models
from django.db.models.functions import Substr


def copy_description_to_name(apps, schema_editor):
    Expense = apps.get_model("finances", "Expense")
    # Copy truncated description to name where name is still empty
    Expense.objects.filter(name="").exclude(description="").update(
        name=Substr("description", 1, 255)
    )
    # Fallback for any remaining blank names
    Expense.objects.filter(name="").update(name="Despesa")


class Migration(migrations.Migration):

    dependencies = [
        ("finances", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="name",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="expense",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.RunPython(copy_description_to_name, migrations.RunPython.noop),
    ]
