# Generated by Django 6.1 on 2026-09-24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_migrate_contract_data'),
        ('finances', '0003_expense_name_alter_expense_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='contract',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense', to='contracts.contract'),
        ),
    ]
