# Generated by Django 6.1 on 2026-09-26 20:02

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0004_alter_expense_contract'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='baseline_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Linha de Base Original'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='total_estimated',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Orçamento Total Estimado'),
        ),
    ]
