# Generated by Django 5.2.4 on 2025-10-21 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Schedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=255, verbose_name="Título do Evento"),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Descrição"),
                ),
                (
                    "start_datetime",
                    models.DateTimeField(verbose_name="Início do Evento"),
                ),
                ("end_datetime", models.DateTimeField(verbose_name="Fim do Evento")),
            ],
            options={
                "verbose_name": "Evento da Agenda",
                "verbose_name_plural": "Eventos da Agenda",
                "ordering": ["start_datetime"],
            },
        ),
    ]
