# Generated by Django 5.2.3 on 2025-07-11 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contracts', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True)),
                ('data_hora', models.DateTimeField()),
                ('tipo', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(blank=True, max_length=50)),
                ('cerimonialista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.cerimonialista')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contracts.contrato')),
            ],
        ),
    ]
