# Generated by Django 5.2.4 on 2025-10-08 03:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("scheduler", "0001_initial"),
        ("weddings", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="schedule",
            name="wedding",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="weddings.wedding",
            ),
        ),
    ]
