# Generated by Django 5.2.4 on 2025-10-25 20:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduler", "0002_initial"),
        ("weddings", "0003_wedding_client"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Título")),
                (
                    "location",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Local"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Descrição"),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("reuniao", "Reunião"),
                            ("pagamento", "Pagamento"),
                            ("visita", "Visita Técnica"),
                            ("degustacao", "Degustação"),
                            ("outro", "Outro"),
                        ],
                        default="outro",
                        max_length=50,
                        verbose_name="Tipo de Evento",
                    ),
                ),
                ("start_time", models.DateTimeField(verbose_name="Início do Evento")),
                (
                    "end_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fim do Evento"
                    ),
                ),
                (
                    "planner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "wedding",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="weddings.wedding",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Schedule",
        ),
    ]
