# Generated by Django 5.2.10 on 2026-05-02 18:52

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finances', '0001_initial'),
        ('tenants', '0001_initial'),
        ('weddings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Nome do fornecedor ou empresa', max_length=255, verbose_name='Nome')),
                ('cnpj', models.CharField(blank=True, help_text='Formato: 00.000.000/0000-00', max_length=18, verbose_name='CNPJ')),
                ('phone', models.CharField(blank=True, help_text='Formato: (00) 00000-0000', max_length=20, verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('website', models.URLField(blank=True, verbose_name='Website')),
                ('address', models.TextField(blank=True, verbose_name='Endereço')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Cidade')),
                ('state', models.CharField(blank=True, max_length=2, validators=[django.core.validators.MaxLengthValidator(2)], verbose_name='Estado (UF)')),
                ('notes', models.TextField(blank=True, help_text='Anotações internas sobre o fornecedor', verbose_name='Observações')),
                ('is_active', models.BooleanField(default=True, help_text='Fornecedor disponível para novos contratos', verbose_name='Ativo')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='tenants.company', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Fornecedor',
                'verbose_name_plural': 'Fornecedores',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Valor exato que consta no documento assinado', max_digits=10, verbose_name='Valor Total do Contrato')),
                ('description', models.TextField(blank=True, verbose_name='Descrição do Contrato')),
                ('status', models.CharField(choices=[('DRAFT', 'Rascunho'), ('PENDING', 'Pendente'), ('SIGNED', 'Assinado'), ('CANCELED', 'Cancelado')], default='DRAFT', max_length=20)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('alert_days_before', models.PositiveIntegerField(default=30)),
                ('signed_date', models.DateField(blank=True, help_text='Data em que o contrato foi formalizado externamente', null=True, verbose_name='Data da Assinatura')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='contracts/%Y/%m/', verbose_name='Arquivo PDF')),
                ('budget_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='finances.budgetcategory', verbose_name='Categoria Orçamentária')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='tenants.company', verbose_name='Empresa')),
                ('wedding', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_records', to='weddings.wedding')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='logistics.supplier', verbose_name='Fornecedor')),
            ],
            options={
                'verbose_name': 'Contrato',
                'verbose_name_plural': 'Contratos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Nome do Item')),
                ('description', models.TextField(blank=True, verbose_name='Descrição/Especificações')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantidade')),
                ('acquisition_status', models.CharField(choices=[('PENDING', 'Pendente'), ('IN_PROGRESS', 'Em Andamento'), ('DONE', 'Concluído')], default='PENDING', max_length=20, verbose_name='Status de Entrega/Logística')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='tenants.company', verbose_name='Empresa')),
                ('contract', models.ForeignKey(blank=True, help_text='Contrato associado a este item', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='logistics.contract', verbose_name='Contrato')),
                ('wedding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='weddings.wedding')),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Itens',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company', 'wedding'], name='logistics_i_company_d2ef2f_idx'), models.Index(fields=['acquisition_status'], name='logistics_i_acquisi_daa75b_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='supplier',
            index=models.Index(fields=['company', 'name'], name='logistics_s_company_c0f8da_idx'),
        ),
        migrations.AddIndex(
            model_name='supplier',
            index=models.Index(fields=['is_active'], name='logistics_s_is_acti_388f6b_idx'),
        ),
        migrations.AddIndex(
            model_name='supplier',
            index=models.Index(fields=['city', 'state'], name='logistics_s_city_41e037_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['company', 'wedding'], name='logistics_c_company_00865a_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['status'], name='logistics_c_status_2f1441_idx'),
        ),
    ]
