# Generated by Django 5.2.10 on 2026-02-04 03:43

import django.core.validators
import django.db.models.deletion
import django.db.models.manager
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finances', '0001_initial'),
        ('weddings', '0002_remove_budgetcategory_budget_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True, verbose_name='Descrição do Contrato')),
                ('status', models.CharField(choices=[('DRAFT', 'Rascunho'), ('PENDING', 'Pendente'), ('SIGNED', 'Assinado'), ('CANCELED', 'Cancelado')], default='DRAFT', max_length=20, verbose_name='Status')),
                ('expiration_date', models.DateField(blank=True, null=True, verbose_name='Data de Vencimento')),
                ('alert_days_before', models.PositiveIntegerField(default=30, verbose_name='Alertar Dias Antes')),
                ('planner_signed_at', models.DateTimeField(blank=True, null=True, verbose_name='Assinado pelo Planner')),
                ('supplier_signed_at', models.DateTimeField(blank=True, null=True, verbose_name='Assinado pelo Fornecedor')),
                ('couple_signed_at', models.DateTimeField(blank=True, null=True, verbose_name='Assinado pelos Noivos')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='contracts/%Y/%m/', verbose_name='Arquivo PDF')),
                ('wedding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='weddings.wedding', verbose_name='Casamento')),
            ],
            options={
                'verbose_name': 'Contrato',
                'verbose_name_plural': 'Contratos',
                'ordering': ['-created_at'],
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=255, verbose_name='Nome do Item')),
                ('description', models.TextField(blank=True, verbose_name='Descrição/Especificações')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantidade')),
                ('acquisition_status', models.CharField(choices=[('PENDING', 'Pendente'), ('IN_PROGRESS', 'Em Andamento'), ('DONE', 'Concluído')], default='PENDING', max_length=20, verbose_name='Status de Entrega/Logística')),
                ('budget_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='finances.budgetcategory', verbose_name='Categoria Orçamental')),
                ('contract', models.ForeignKey(blank=True, help_text='Contrato associado a este item', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='logistics.contract', verbose_name='Contrato')),
                ('wedding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='weddings.wedding', verbose_name='Casamento')),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Itens',
                'ordering': ['-created_at'],
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(help_text='Nome do fornecedor ou empresa', max_length=255, verbose_name='Nome')),
                ('cnpj', models.CharField(blank=True, help_text='Formato: 00.000.000/0000-00', max_length=18, verbose_name='CNPJ')),
                ('phone', models.CharField(blank=True, help_text='Formato: (00) 00000-0000', max_length=20, verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('website', models.URLField(blank=True, verbose_name='Website')),
                ('address', models.TextField(blank=True, verbose_name='Endereço')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Cidade')),
                ('state', models.CharField(blank=True, max_length=2, validators=[django.core.validators.MaxLengthValidator(2)], verbose_name='Estado (UF)')),
                ('notes', models.TextField(blank=True, help_text='Anotações internas sobre o fornecedor', verbose_name='Observações')),
                ('is_active', models.BooleanField(default=True, help_text='Fornecedor disponível para novos contratos', verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Fornecedor',
                'verbose_name_plural': 'Fornecedores',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='logistics_s_name_19ad49_idx'), models.Index(fields=['is_active'], name='logistics_s_is_acti_388f6b_idx'), models.Index(fields=['city', 'state'], name='logistics_s_city_41e037_idx')],
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='contract',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='logistics.supplier', verbose_name='Fornecedor'),
        ),
    ]
