# Generated by Django 5.2.10 on 2026-02-16 19:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finances', '0002_initial'),
        ('logistics', '0001_initial'),
        ('weddings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='wedding',
            field=models.ForeignKey(help_text='Vincula o registro a um evento específico gerenciado pelo Planner.', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='weddings.wedding', verbose_name='Casamento'),
        ),
        migrations.AddField(
            model_name='item',
            name='budget_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='finances.budgetcategory', verbose_name='Categoria Orçamental'),
        ),
        migrations.AddField(
            model_name='item',
            name='contract',
            field=models.ForeignKey(blank=True, help_text='Contrato associado a este item', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='logistics.contract', verbose_name='Contrato'),
        ),
        migrations.AddField(
            model_name='item',
            name='wedding',
            field=models.ForeignKey(help_text='Vincula o registro a um evento específico gerenciado pelo Planner.', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='weddings.wedding', verbose_name='Casamento'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='planner',
            field=models.ForeignKey(help_text='Identifica o Planner dono deste registro para isolamento de dados.', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to=settings.AUTH_USER_MODEL, verbose_name='Planner Responsável'),
        ),
        migrations.AddField(
            model_name='contract',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='logistics.supplier', verbose_name='Fornecedor'),
        ),
        migrations.AddIndex(
            model_name='supplier',
            index=models.Index(fields=['planner', 'name'], name='logistics_s_planner_1d51f0_idx'),
        ),
        migrations.AddIndex(
            model_name='supplier',
            index=models.Index(fields=['is_active'], name='logistics_s_is_acti_388f6b_idx'),
        ),
        migrations.AddIndex(
            model_name='supplier',
            index=models.Index(fields=['city', 'state'], name='logistics_s_city_41e037_idx'),
        ),
    ]
