# Generated by Django 5.2.10 on 2026-02-04 04:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finances', '0002_initial'),
        ('logistics', '0001_initial'),
        ('weddings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='wedding',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='weddings.wedding', verbose_name='Casamento'),
        ),
        migrations.AddField(
            model_name='item',
            name='budget_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='finances.budgetcategory', verbose_name='Categoria Orçamental'),
        ),
        migrations.AddField(
            model_name='item',
            name='contract',
            field=models.ForeignKey(blank=True, help_text='Contrato associado a este item', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='logistics.contract', verbose_name='Contrato'),
        ),
        migrations.AddField(
            model_name='item',
            name='wedding',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='weddings.wedding', verbose_name='Casamento'),
        ),
        migrations.AddIndex(
            model_name='supplier',
            index=models.Index(fields=['name'], name='logistics_s_name_19ad49_idx'),
        ),
        migrations.AddIndex(
            model_name='supplier',
            index=models.Index(fields=['is_active'], name='logistics_s_is_acti_388f6b_idx'),
        ),
        migrations.AddIndex(
            model_name='supplier',
            index=models.Index(fields=['city', 'state'], name='logistics_s_city_41e037_idx'),
        ),
        migrations.AddField(
            model_name='contract',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='logistics.supplier', verbose_name='Fornecedor'),
        ),
    ]
