# Generated by Django 5.2.10 on 2026-05-09 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0002_add_contract_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='budget_category',
        ),
    ]
