# Generated by Django 5.2.10 on 2026-02-20 08:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0002_initial'),
        ('weddings', '0002_alter_wedding_managers_remove_wedding_deleted_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='contract',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='item',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='supplier',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='contract',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='item',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='item',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='is_deleted',
        ),
        migrations.AlterField(
            model_name='contract',
            name='wedding',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='weddings.wedding'),
        ),
        migrations.AlterField(
            model_name='item',
            name='wedding',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='weddings.wedding'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='planner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to=settings.AUTH_USER_MODEL),
        ),
    ]
