# Generated by Django 5.2.10 on 2026-05-09 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0003_remove_contract_budget_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='name',
            field=models.CharField(default='', max_length=255, verbose_name='Nome'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contract',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Descrição do Contrato'),
        ),
    ]
