# Generated by Django 5.2.10 on 2026-04-06 03:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0003_alter_budgetcategory_managers_and_more'),
        ('logistics', '0003_alter_contract_managers_alter_item_managers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='budget_category',
        ),
        migrations.AddField(
            model_name='contract',
            name='budget_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='finances.budgetcategory', verbose_name='Categoria Orçamentária'),
        ),
    ]
