# Generated by Django 5.2.10 on 2026-05-09 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0004_add_contract_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Vincula este contrato como aditivo de um contrato principal.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='addendums', to='logistics.contract', verbose_name='Contrato Original (Pai)'),
        ),
    ]
