# Generated by Django 5.2.10 on 2026-04-07 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0004_remove_item_budget_category_contract_budget_category'),
        ('weddings', '0004_alter_wedding_planner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='wedding',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_records', to='weddings.wedding'),
        ),
    ]
