# Generated by Django 5.2.10 on 2026-04-26 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0005_alter_contract_wedding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='logistics.supplier', verbose_name='Fornecedor'),
        ),
    ]
