# Generated by Django 5.2.10 on 2026-06-08 18:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0005_change_parent_to_protect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='cnpj',
            field=models.CharField(blank=True, help_text='Formato: 00.000.000/0000-00', max_length=18, validators=[django.core.validators.RegexValidator(message='CNPJ deve estar no formato XX.XXX.XXX/XXXX-XX.', regex='^(\\d{2}\\.\\d{3}\\.\\d{3}/\\d{4}-\\d{2})?$')], verbose_name='CNPJ'),
        ),
    ]
