# Generated by Django 5.2.10 on 2026-06-09 23:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0007_alter_supplier_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='contracts/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'png', 'jpg', 'jpeg'], message='Tipo de arquivo não suportado. Use PDF, PNG ou JPEG.')], verbose_name='Arquivo PDF'),
        ),
    ]
