# Generated by Django 5.2.10 on 2026-06-10 17:22

import apps.core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0009_alter_contract_pdf_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='pdf_file',
            field=models.FileField(blank=True, help_text='Formatos aceitos: PDF, PNG, JPEG. Tamanho máximo: 10MB.', null=True, upload_to='contracts/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'png', 'jpg', 'jpeg'], message='Tipo de arquivo não suportado. Use PDF, PNG ou JPEG.'), apps.core.validators.MaxFileSizeValidator(10485760)], verbose_name='Arquivo PDF'),
        ),
    ]
