# Generated by Django 6.1 on 2026-09-24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_migrate_contract_data'),
        # Ordem determinística: Expense referencia logistics.contract até
        # finances.0004; deletar o modelo legado antes quebra o replay
        # (sqlite recria a tabela de Expense resolvendo a FK).
        ('finances', '0003_expense_name_alter_expense_description'),
        ('logistics', '0014_rename_item_to_supplyitem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplyitem',
            name='contract',
            field=models.ForeignKey(blank=True, help_text='Contrato associado a este item', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='contracts.contract', verbose_name='Contrato'),
        ),
        migrations.RemoveIndex(
            model_name='contract',
            name='logistics_c_company_00865a_idx',
        ),
        migrations.RemoveIndex(
            model_name='contract',
            name='logistics_c_status_2f1441_idx',
        ),
        migrations.RemoveIndex(
            model_name='contractaddendum',
            name='logistics_c_company_c1226c_idx',
        ),
        migrations.RemoveIndex(
            model_name='contractaddendum',
            name='logistics_c_contrac_af5139_idx',
        ),
        migrations.RemoveIndex(
            model_name='contractaddendum',
            name='logistics_c_status_d8c1d7_idx',
        ),
        migrations.RemoveField(
            model_name='contractaddendum',
            name='company',
        ),
        migrations.RemoveField(
            model_name='contractaddendum',
            name='contract',
        ),
        migrations.RemoveField(
            model_name='contractaddendum',
            name='wedding',
        ),
        migrations.DeleteModel(
            name='ContractAddendum',
        ),
        migrations.DeleteModel(
            name='Contract',
        ),
    ]
