# Generated by Django 6.1 on 2026-09-26 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0005_move_supplier_to_suppliers'),
        ('logistics', '0016_remove_supplier_state'),
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplyitem',
            name='supplier',
            field=models.ForeignKey(blank=True, help_text='Fornecedor associado a este item', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supply_items', to='suppliers.supplier', verbose_name='Fornecedor'),
        ),
        migrations.AlterField(
            model_name='supplyitem',
            name='contract',
            field=models.ForeignKey(blank=True, help_text='Contrato formal associado a este item', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supply_items', to='contracts.contract', verbose_name='Contrato Formal'),
        ),
    ]
