# Generated by Django 6.1 on 2026-09-27 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0005_move_supplier_to_suppliers'),
        ('logistics', '0017_supplyitem_supplier_alter_supplyitem_contract'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplyitem',
            name='supplier',
        ),
        migrations.AlterField(
            model_name='supplyitem',
            name='contract',
            field=models.ForeignKey(blank=True, help_text='Contrato associado a este item', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='contracts.contract', verbose_name='Contrato'),
        ),
    ]
