# Generated by Django 6.0.8 on 2026-08-08 18:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('message', models.TextField(verbose_name='Mensagem')),
                ('type', models.CharField(choices=[('OVERDUE_INSTALLMENT', 'Parcela Vencida'), ('UPCOMING_INSTALLMENT', 'Parcela a Vencer'), ('EXPIRING_CONTRACT', 'Contrato Prestes a Vencer'), ('TASK_DEADLINE', 'Prazo de Tarefa'), ('CHECKLIST_ITEM_OVERDUE', 'Item de Checklist Vencido'), ('GENERAL', 'Geral')], default='GENERAL', max_length=50, verbose_name='Tipo')),
                ('is_read', models.BooleanField(db_index=True, default=False, verbose_name='Lida')),
                ('link', models.CharField(blank=True, default='', max_length=500, verbose_name='Link')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Lida em')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='tenants.company', verbose_name='Empresa')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Notificação',
                'verbose_name_plural': 'Notificações',
                'db_table': 'notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company', 'user', 'is_read'], name='notificatio_company_ca158b_idx')],
            },
        ),
    ]
