# Generated by Django 6.0.8 on 2026-08-08 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='target_id',
            field=models.UUIDField(blank=True, db_index=True, null=True, verbose_name='ID do Alvo'),
        ),
        migrations.AddField(
            model_name='notification',
            name='target_type',
            field=models.CharField(blank=True, choices=[('installment', 'Parcela'), ('expense', 'Despesa'), ('task', 'Tarefa'), ('contract', 'Contrato'), ('wedding', 'Casamento'), ('general', 'Geral')], default='', max_length=50, verbose_name='Tipo de Alvo'),
        ),
        migrations.AddField(
            model_name='notification',
            name='wedding_id',
            field=models.UUIDField(blank=True, db_index=True, null=True, verbose_name='ID do Casamento'),
        ),
    ]
