# Generated by Django 6.1 on 2026-09-26 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_notification_wedding_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('OVERDUE_INSTALLMENT', 'Parcela Vencida'), ('UPCOMING_INSTALLMENT', 'Parcela a Vencer'), ('EXPIRING_CONTRACT', 'Contrato Prestes a Vencer'), ('TASK_DEADLINE', 'Prazo de Tarefa'), ('CHECKLIST_ITEM_OVERDUE', 'Item de Checklist Vencido'), ('ADDENDUM_SIGNED', 'Termo Aditivo Assinado'), ('GENERAL', 'Geral')], default='GENERAL', max_length=50, verbose_name='Tipo'),
        ),
    ]
