# Generated by Django 5.2.3 on 2025-07-15 04:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("client", "0001_initial"),
        ("contracts", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Wedding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("groom_name", models.CharField(blank=True, max_length=100, null=True)),
                ("bride_name", models.CharField(blank=True, max_length=100, null=True)),
                ("date", models.DateField()),
                ("location", models.CharField(max_length=255)),
                ("clients", models.ManyToManyField(blank=True, to="client.client")),
                (
                    "contract",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contracts.contract",
                    ),
                ),
                (
                    "planner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.planner"
                    ),
                ),
            ],
        ),
    ]
