# Generated by Django 5.2.4 on 2025-11-17 01:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Wedding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Data e hora em que este objeto foi criado.",
                        verbose_name="Data de Criação",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Data e hora em que foi atualizado pela última vez.",
                        verbose_name="Última Atualização",
                    ),
                ),
                ("groom_name", models.CharField(max_length=100)),
                ("bride_name", models.CharField(max_length=100)),
                ("date", models.DateField()),
                ("location", models.CharField(max_length=255)),
                ("budget", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("IN_PROGRESS", "Em Andamento"),
                            ("COMPLETED", "Concluído"),
                            ("CANCELED", "Cancelado"),
                        ],
                        default="IN_PROGRESS",
                        max_length=20,
                    ),
                ),
                (
                    "planner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
