# Generated by Django 5.2.4 on 2025-08-02 01:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0001_initial"),
        ("weddings", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="wedding",
            name="contract",
        ),
        migrations.AlterField(
            model_name="wedding",
            name="client",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="weddings",
                to="client.client",
            ),
        ),
    ]
