# Generated by Django 5.2.7 on 2025-10-24 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_initial'),
        ('weddings', '0002_remove_wedding_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='wedding',
            name='client',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weddings', to='client.client'),
        ),
    ]
