# Generated by Django 5.2.4 on 2025-11-08 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("weddings", "0003_wedding_client"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wedding",
            name="bride_name",
            field=models.CharField(default="Noiva Padrão", max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="wedding",
            name="groom_name",
            field=models.CharField(default="Noivo Padrão", max_length=100),
            preserve_default=False,
        ),
    ]
