# Generated by Django 5.2.4 on 2025-11-11 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("weddings", "0005_wedding_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="wedding",
            name="client",
        ),
    ]
