# Generated by Django 5.2.4 on 2025-11-12 13:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("weddings", "0006_remove_wedding_client"),
    ]

    operations = [
        migrations.AddField(
            model_name="wedding",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                help_text="Data e hora em que este objeto foi criado.",
                verbose_name="Data de Criação",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="wedding",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Data e hora em que foi atualizado pela última vez.",
                verbose_name="Última Atualização",
            ),
        ),
    ]
