# Generated by Django 5.2.10 on 2026-06-08 17:42

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='company',
            field=models.ForeignKey(help_text='Empresa (tenant) à qual o usuário pertence.', on_delete=django.db.models.deletion.PROTECT, related_name='users', to='tenants.company', verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp de criação do registro.'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Data de criação da conta.', verbose_name='Data de Cadastro'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(help_text='Nome próprio do usuário.', max_length=150, verbose_name='Primeiro Nome'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Indica se o usuário está ativo no sistema.', verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Indica se o usuário pode acessar o admin do Django.', verbose_name='Status da Equipe'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(help_text='Sobrenome do usuário.', max_length=150, verbose_name='Sobrenome'),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp da última atualização do registro.'),
        ),
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Identificador público único do usuário.', unique=True),
        ),
    ]
