# Generated by Django 6.0.8 on 2026-08-10 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_company_alter_user_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_verified_at',
            field=models.DateTimeField(blank=True, help_text='Data e hora da confirmação do e-mail.', null=True, verbose_name='Data de Verificação do E-mail'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_email_verified',
            field=models.BooleanField(default=False, help_text='Indica se o e-mail do usuário foi verificado.', verbose_name='E-mail Verificado'),
        ),
    ]
