# Generated by Django 5.2.4 on 2025-10-23 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
        ('weddings', '0002_remove_wedding_client'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Client',
        ),
    ]
