# Generated by Django 5.2.10 on 2026-04-28 17:51

import apps.events.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Nome do Evento')),
                ('event_type', models.CharField(choices=[('WEDDING', 'Casamento'), ('CORPORATE', 'Corporativo'), ('SOCIAL', 'Social (Aniversário, etc)'), ('OTHER', 'Outro')], default='WEDDING', max_length=20)),
                ('date', models.DateField(validators=[apps.events.models.validate_future_date])),
                ('location', models.CharField(max_length=255)),
                ('expected_guests', models.PositiveIntegerField(blank=True, null=True, verbose_name='Número de Convidados')),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'Em Andamento'), ('COMPLETED', 'Concluído'), ('CANCELED', 'Cancelado')], default='IN_PROGRESS', max_length=20)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='tenants.company', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='WeddingDetail',
            fields=[
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='wedding_detail', serialize=False, to='events.event')),
                ('groom_name', models.CharField(max_length=100, verbose_name='Nome do Noivo')),
                ('bride_name', models.CharField(max_length=100, verbose_name='Nome da Noiva')),
            ],
            options={
                'verbose_name': 'Detalhe de Casamento',
                'verbose_name_plural': 'Detalhes de Casamentos',
            },
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['company', 'status'], name='events_even_company_6200ff_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['date'], name='events_even_date_5e8e1c_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['event_type'], name='events_even_event_t_a87b5c_idx'),
        ),
    ]
