# Generated by Django 5.2.10 on 2026-04-28 17:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('event_type', models.CharField(choices=[('MEETING', 'Reunião'), ('VISIT', 'Visita Técnica'), ('DEGUSTATION', 'Degustação'), ('CEREMONY', 'Cerimônia'), ('OTHER', 'Outro')], default='MEETING', max_length=20)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('location', models.CharField(blank=True, max_length=255)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='tenants.company', verbose_name='Empresa')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='events.event')),
            ],
            options={
                'verbose_name': 'Compromisso',
                'verbose_name_plural': 'Compromissos',
                'ordering': ['start_time'],
                'indexes': [models.Index(fields=['company', 'start_time'], name='scheduler_a_company_0bd8ba_idx'), models.Index(fields=['event', 'start_time'], name='scheduler_a_event_i_e5df3c_idx'), models.Index(fields=['event_type'], name='scheduler_a_event_t_97fb39_idx'), models.Index(fields=['start_time'], name='scheduler_a_start_t_e84622_idx')],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, verbose_name='Título da Tarefa')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição detalhada')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Prazo Estimado')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Concluída?')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='tenants.company', verbose_name='Empresa')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='events.event')),
            ],
            options={
                'verbose_name': 'Tarefa',
                'verbose_name_plural': 'Tarefas',
                'ordering': ['is_completed', 'due_date', 'created_at'],
                'indexes': [models.Index(fields=['company', 'is_completed'], name='scheduler_t_company_d1bbdc_idx'), models.Index(fields=['event', 'is_completed'], name='scheduler_t_event_i_7dccdb_idx'), models.Index(fields=['due_date'], name='scheduler_t_due_dat_d4fac0_idx')],
            },
        ),
    ]
