# Generated by Django 5.2.10 on 2026-05-02 15:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        ('weddings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='Local')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('event_type', models.CharField(choices=[('reuniao', 'Reunião'), ('pagamento', 'Pagamento'), ('visita', 'Visita Técnica'), ('degustacao', 'Degustação'), ('outro', 'Outro')], default='outro', max_length=50, verbose_name='Tipo de Evento')),
                ('start_time', models.DateTimeField(verbose_name='Início do Evento')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Fim do Evento')),
                ('reminder_enabled', models.BooleanField(default=False, help_text='Enviar lembrete automático', verbose_name='Lembrete Ativo')),
                ('reminder_minutes_before', models.PositiveIntegerField(default=60, help_text='Quantos minutos antes do evento enviar lembrete', verbose_name='Lembrete (minutos antes)')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='tenants.company', verbose_name='Empresa')),
                ('wedding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='weddings.wedding')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['start_time'],
                'indexes': [models.Index(fields=['company', 'start_time'], name='scheduler_e_company_678ac6_idx'), models.Index(fields=['wedding', 'start_time'], name='scheduler_e_wedding_335246_idx'), models.Index(fields=['event_type'], name='scheduler_e_event_t_e38949_idx'), models.Index(fields=['start_time'], name='scheduler_e_start_t_b3de21_idx')],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, verbose_name='Título da Tarefa')),
                ('description', models.TextField(blank=True, verbose_name='Descrição detalhada')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Prazo Estimado')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Concluída?')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='tenants.company', verbose_name='Empresa')),
                ('wedding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='weddings.wedding')),
            ],
            options={
                'verbose_name': 'Tarefa',
                'verbose_name_plural': 'Tarefas',
                'ordering': ['is_completed', 'due_date', 'created_at'],
                'indexes': [models.Index(fields=['company', 'is_completed'], name='scheduler_t_company_d1bbdc_idx'), models.Index(fields=['wedding', 'is_completed'], name='scheduler_t_wedding_729829_idx'), models.Index(fields=['due_date'], name='scheduler_t_due_dat_d4fac0_idx')],
            },
        ),
    ]
