# Generated by Django 5.2.9 on 2026-02-01 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='Local')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('event_type', models.CharField(choices=[('reuniao', 'Reunião'), ('pagamento', 'Pagamento'), ('visita', 'Visita Técnica'), ('degustacao', 'Degustação'), ('outro', 'Outro')], default='outro', max_length=50, verbose_name='Tipo de Evento')),
                ('start_time', models.DateTimeField(verbose_name='Início do Evento')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Fim do Evento')),
                ('reminder_enabled', models.BooleanField(default=False, help_text='Enviar lembrete automático', verbose_name='Lembrete Ativo')),
                ('reminder_minutes_before', models.PositiveIntegerField(default=60, help_text='Quantos minutos antes do evento enviar lembrete', verbose_name='Lembrete (minutos antes)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['start_time'],
            },
        ),
    ]
