# Generated by Django 5.2.9 on 2026-02-02 01:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scheduler', '0001_initial'),
        ('weddings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='planner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='wedding',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='weddings.wedding'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['planner', 'start_time'], name='scheduler_e_planner_1232f8_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['wedding', 'start_time'], name='scheduler_e_wedding_335246_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['event_type'], name='scheduler_e_event_t_e38949_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['start_time'], name='scheduler_e_start_t_b3de21_idx'),
        ),
    ]
