# Generated by Django 5.2.10 on 2026-05-17 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='recurrence_rule',
            field=models.CharField(choices=[('none', 'Não recorrente'), ('semanal', 'Semanal'), ('quinzenal', 'Quinzenal'), ('mensal', 'Mensal')], default='none', help_text='Frequência com que o evento se repete', max_length=20, verbose_name='Regra de Recorrência'),
        ),
    ]
