# Generated by Django 5.2.10 on 2026-02-20 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_initial'),
        ('weddings', '0002_alter_wedding_managers_remove_wedding_deleted_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='wedding',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='weddings.wedding'),
        ),
    ]
