# Generated by Django 5.2.10 on 2026-06-12 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0003_expense_name_alter_expense_description'),
        ('scheduler', '0002_event_recurrence_rule'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='source_installment',
            field=models.ForeignKey(blank=True, help_text='Parcela financeira que gerou este evento (apenas PAYMENT)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='finances.installment', verbose_name='Parcela de origem'),
        ),
    ]
