# Generated by Django 5.2.10 on 2026-04-12 12:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0004_alter_event_planner'),
        ('weddings', '0004_alter_wedding_planner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, verbose_name='Título da Tarefa')),
                ('description', models.TextField(blank=True, verbose_name='Descrição detalhada')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Prazo Estimado')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Concluída?')),
                ('planner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_records', to=settings.AUTH_USER_MODEL)),
                ('wedding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='weddings.wedding')),
            ],
            options={
                'verbose_name': 'Tarefa',
                'verbose_name_plural': 'Tarefas',
                'ordering': ['is_completed', 'due_date', 'created_at'],
                'indexes': [models.Index(fields=['planner', 'is_completed'], name='scheduler_t_planner_37be98_idx'), models.Index(fields=['wedding', 'is_completed'], name='scheduler_t_wedding_729829_idx'), models.Index(fields=['due_date'], name='scheduler_t_due_dat_d4fac0_idx')],
            },
        ),
    ]
