# Generated by Django 5.2.10 on 2026-04-26 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0006_alter_event_planner_alter_task_planner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição detalhada'),
        ),
    ]
