# Generated by Django 5.2.10 on 2026-04-26 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0007_alter_task_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Descrição detalhada'),
        ),
    ]
