# Generated by Django 5.2.9 on 2026-02-01 21:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nome do fornecedor ou empresa', max_length=255, verbose_name='Nome')),
                ('cnpj', models.CharField(blank=True, help_text='Formato: 00.000.000/0000-00', max_length=18, verbose_name='CNPJ')),
                ('phone', models.CharField(blank=True, help_text='Formato: (00) 00000-0000', max_length=20, verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('website', models.URLField(blank=True, verbose_name='Website')),
                ('address', models.TextField(blank=True, verbose_name='Endereço')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Cidade')),
                ('state', models.CharField(blank=True, max_length=2, validators=[django.core.validators.MaxLengthValidator(2)], verbose_name='Estado (UF)')),
                ('rating', models.DecimalField(blank=True, decimal_places=1, help_text='Nota de 0.0 a 5.0', max_digits=2, null=True, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Avaliação')),
                ('notes', models.TextField(blank=True, help_text='Anotações internas sobre o fornecedor', verbose_name='Observações')),
                ('is_active', models.BooleanField(default=True, help_text='Fornecedor disponível para novos contratos', verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Fornecedor',
                'verbose_name_plural': 'Fornecedores',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='suppliers_s_name_6277a9_idx'), models.Index(fields=['is_active'], name='suppliers_s_is_acti_a75d30_idx'), models.Index(fields=['city', 'state'], name='suppliers_s_city_3e1b8f_idx')],
            },
        ),
    ]
