# Generated by Django 6.1 on 2026-09-26 20:10

import apps.suppliers.validators
import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='Supplier',
                    fields=[
                        ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                        ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                        ('name', models.CharField(help_text='Nome do fornecedor ou empresa', max_length=255, verbose_name='Nome')),
                        ('cnpj', models.CharField(blank=True, help_text='Formato: 00.000.000/0000-00', max_length=18, validators=[apps.suppliers.validators.validate_cnpj_modulo11], verbose_name='CNPJ')),
                        ('phone', models.CharField(blank=True, help_text='Formato: (00) 00000-0000', max_length=20, verbose_name='Telefone')),
                        ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                        ('website', models.URLField(blank=True, verbose_name='Website')),
                        ('address', models.TextField(blank=True, verbose_name='Endereço')),
                        ('city', models.CharField(blank=True, max_length=100, verbose_name='Cidade')),
                        ('state', models.CharField(blank=True, max_length=2, validators=[django.core.validators.MinLengthValidator(2), django.core.validators.MaxLengthValidator(2)], verbose_name='Estado (UF)')),
                        ('notes', models.TextField(blank=True, help_text='Anotações internas sobre o fornecedor', verbose_name='Observações')),
                        ('is_active', models.BooleanField(default=True, help_text='Fornecedor disponível para novos contratos', verbose_name='Ativo')),
                        ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='tenants.company', verbose_name='Empresa')),
                    ],
                    options={
                        'verbose_name': 'Fornecedor',
                        'verbose_name_plural': 'Fornecedores',
                        'db_table': 'logistics_supplier',
                        'ordering': ['name'],
                        'indexes': [models.Index(fields=['company', 'name'], name='logistics_s_company_c0f8da_idx'), models.Index(fields=['is_active'], name='logistics_s_is_acti_388f6b_idx'), models.Index(fields=['city', 'state'], name='logistics_s_city_41e037_idx')],
                    },
                ),
            ],
            database_operations=[],
        ),
    ]
