# Generated by Django 5.2.3 on 2025-07-11 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0002_alter_contrato_cliente"),
        ("items", "0002_alter_item_fornecedor"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Cliente",
        ),
        migrations.DeleteModel(
            name="Fornecedor",
        ),
    ]
