# Generated by Django 5.2.10 on 2026-02-04 04:05

import django.db.models.deletion
import django.db.models.manager
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wedding',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('groom_name', models.CharField(max_length=100)),
                ('bride_name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('location', models.CharField(max_length=255)),
                ('expected_guests', models.PositiveIntegerField(blank=True, help_text='Quantidade estimada de convidados', null=True, verbose_name='Número de Convidados')),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'Em Andamento'), ('COMPLETED', 'Concluído'), ('CANCELED', 'Cancelado')], default='IN_PROGRESS', max_length=20)),
                ('planner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Casamento',
                'verbose_name_plural': 'Casamentos',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['planner', 'status'], name='weddings_we_planner_bc7e09_idx'), models.Index(fields=['date'], name='weddings_we_date_feb81a_idx'), models.Index(fields=['status'], name='weddings_we_status_a7f36b_idx')],
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
