# Generated by Django 5.2.10 on 2026-05-02 15:00

import apps.weddings.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wedding',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groom_name', models.CharField(max_length=100)),
                ('bride_name', models.CharField(max_length=100)),
                ('date', models.DateField(validators=[apps.weddings.models.validate_future_date])),
                ('location', models.CharField(max_length=255)),
                ('expected_guests', models.PositiveIntegerField(blank=True, help_text='Quantidade estimada de convidados', null=True, verbose_name='Número de Convidados')),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'Em Andamento'), ('COMPLETED', 'Concluído'), ('CANCELED', 'Cancelado')], default='IN_PROGRESS', max_length=20)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='tenants.company', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Casamento',
                'verbose_name_plural': 'Casamentos',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['company', 'status'], name='weddings_we_company_6bf092_idx'), models.Index(fields=['date'], name='weddings_we_date_feb81a_idx'), models.Index(fields=['status'], name='weddings_we_status_a7f36b_idx')],
            },
        ),
    ]
