# Generated by Django 5.2.9 on 2026-02-02 01:49

import django.core.validators
import django.db.models.deletion
import uuid6
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wedding',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('groom_name', models.CharField(max_length=100)),
                ('bride_name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('location', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'Em Andamento'), ('COMPLETED', 'Concluído'), ('CANCELED', 'Cancelado')], default='IN_PROGRESS', max_length=20)),
                ('planner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Casamento',
                'verbose_name_plural': 'Casamentos',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_estimated', models.DecimalField(decimal_places=2, help_text='Orçamento planejado total para o evento', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Valor Estimado Total')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('wedding', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='budget', to='weddings.wedding', verbose_name='Casamento')),
            ],
            options={
                'verbose_name': 'Orçamento',
                'verbose_name_plural': 'Orçamentos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BudgetCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ex: Buffet, Decoração, Fotografia', max_length=100, verbose_name='Nome da Categoria')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('allocated_budget', models.DecimalField(decimal_places=2, help_text='Quanto foi reservado para esta categoria', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Orçamento Alocado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='weddings.budget', verbose_name='Orçamento')),
            ],
            options={
                'verbose_name': 'Categoria de Orçamento',
                'verbose_name_plural': 'Categorias de Orçamento',
                'ordering': ['name'],
                'unique_together': {('budget', 'name')},
            },
        ),
        migrations.AddIndex(
            model_name='wedding',
            index=models.Index(fields=['planner', 'status'], name='weddings_we_planner_bc7e09_idx'),
        ),
        migrations.AddIndex(
            model_name='wedding',
            index=models.Index(fields=['date'], name='weddings_we_date_feb81a_idx'),
        ),
        migrations.AddIndex(
            model_name='wedding',
            index=models.Index(fields=['status'], name='weddings_we_status_a7f36b_idx'),
        ),
    ]
