# Generated by Django 5.2.10 on 2026-07-02 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weddings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wedding',
            name='template',
            field=models.CharField(blank=True, help_text='Template aplicado na criação do casamento', max_length=50, null=True, verbose_name='Modelo de Cronograma'),
        ),
    ]
