# Generated by Django 5.2.10 on 2026-02-04 03:43

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weddings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budgetcategory',
            name='budget',
        ),
        migrations.AlterUniqueTogether(
            name='budgetcategory',
            unique_together=None,
        ),
        migrations.AlterModelManagers(
            name='wedding',
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='wedding',
            name='expected_guests',
            field=models.PositiveIntegerField(blank=True, help_text='Quantidade estimada de convidados', null=True, verbose_name='Número de Convidados'),
        ),
        migrations.DeleteModel(
            name='Budget',
        ),
        migrations.DeleteModel(
            name='BudgetCategory',
        ),
    ]
