# Generated by Django 5.2.10 on 2026-02-20 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weddings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='wedding',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='wedding',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='wedding',
            name='is_deleted',
        ),
    ]
