# Generated by Django 6.1 on 2026-09-07 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weddings', '0002_wedding_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wedding',
            name='date',
            field=models.DateField(),
        ),
    ]
