# Generated by Django 5.2.10 on 2026-02-22 06:54

import apps.weddings.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weddings', '0002_alter_wedding_managers_remove_wedding_deleted_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wedding',
            name='date',
            field=models.DateField(validators=[apps.weddings.models.validate_future_date]),
        ),
    ]
