# Generated by Django 6.1 on 2026-09-23 22:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
        ('weddings', '0003_alter_wedding_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='wedding',
            name='client_cpf',
            field=models.CharField(blank=True, default='', max_length=14, verbose_name='CPF do Contratante'),
        ),
        migrations.AddField(
            model_name='wedding',
            name='client_email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='E-mail do Contratante'),
        ),
        migrations.AddField(
            model_name='wedding',
            name='client_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Nome do Contratante'),
        ),
        migrations.AddField(
            model_name='wedding',
            name='client_phone',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Telefone do Contratante'),
        ),
        migrations.AddField(
            model_name='wedding',
            name='client_role',
            field=models.CharField(blank=True, default='NOIVO', max_length=50, verbose_name='Papel do Contratante'),
        ),
        migrations.AddField(
            model_name='wedding',
            name='days_before_in_progress',
            field=models.PositiveIntegerField(default=7, verbose_name='Dias para Reta Final'),
        ),
        migrations.AlterField(
            model_name='wedding',
            name='status',
            field=models.CharField(choices=[('PROPOSAL', 'Proposta'), ('IN_PROGRESS', 'Em Andamento'), ('COMPLETED', 'Concluído'), ('CANCELED', 'Cancelado')], default='IN_PROGRESS', max_length=20),
        ),
        migrations.CreateModel(
            name='PlannerContract',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service_tier', models.CharField(choices=[('COMPLETA', 'Assessoria Completa'), ('PARCIAL', 'Assessoria Parcial'), ('FINAL', 'Assessoria do Dia/Final')], default='COMPLETA', max_length=50, verbose_name='Tipo de Assessoria')),
                ('effective_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor dos Honorários')),
                ('installments_count', models.PositiveIntegerField(default=1, verbose_name='Número de Parcelas')),
                ('signed_date', models.DateField(blank=True, null=True, verbose_name='Data da Assinatura')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='planner_contracts/%Y/%m/', verbose_name='Arquivo PDF do Contrato')),
                ('status', models.CharField(choices=[('DRAFT', 'Rascunho'), ('SIGNED', 'Assinado'), ('CANCELED', 'Cancelado')], default='DRAFT', max_length=20, verbose_name='Status do Contrato')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='tenants.company', verbose_name='Empresa')),
                ('wedding', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='planner_contract', to='weddings.wedding', verbose_name='Casamento')),
            ],
            options={
                'verbose_name': 'Contrato de Assessoria',
                'verbose_name_plural': 'Contratos de Assessoria',
                'indexes': [models.Index(fields=['company', 'status'], name='weddings_pl_company_4b67ac_idx'), models.Index(fields=['wedding'], name='weddings_pl_wedding_612423_idx')],
            },
        ),
    ]
