# Generated by Django 6.1 on 2026-09-24

import django.db.models.deletion
import uuid
from django.db import migrations, models


def populate_wedding_participants(apps, schema_editor):
    """
    Popula Client e WeddingClient a partir dos dados legados dos casamentos existentes.
    """
    Wedding = apps.get_model("weddings", "Wedding")
    Client = apps.get_model("clients", "Client")
    WeddingClient = apps.get_model("weddings", "WeddingClient")

    for wedding in Wedding.objects.all():
        bride_name = wedding.bride_name.strip() if wedding.bride_name else ""
        if bride_name:
            is_bride_client = (
                wedding.client_role in ("NOIVA", "BRIDE")
                or (wedding.client_name and wedding.client_name.strip() == bride_name)
            )
            bride_cpf = wedding.client_cpf.strip() if is_bride_client and wedding.client_cpf else ""
            bride_email = wedding.client_email.strip().lower() if is_bride_client and wedding.client_email else ""
            bride_phone = wedding.client_phone.strip() if is_bride_client and wedding.client_phone else ""

            bride_client, _ = Client.objects.get_or_create(
                company_id=wedding.company_id,
                name=bride_name,
                defaults={
                    "cpf": bride_cpf,
                    "email": bride_email,
                    "phone": bride_phone,
                },
            )
            WeddingClient.objects.get_or_create(
                company_id=wedding.company_id,
                wedding_id=wedding.id,
                client_id=bride_client.id,
                role="BRIDE",
                defaults={
                    "is_primary_signatory": bool(is_bride_client),
                },
            )

        groom_name = wedding.groom_name.strip() if wedding.groom_name else ""
        if groom_name:
            is_groom_client = (
                wedding.client_role in ("NOIVO", "GROOM")
                or (wedding.client_name and wedding.client_name.strip() == groom_name)
            )
            groom_cpf = wedding.client_cpf.strip() if is_groom_client and wedding.client_cpf else ""
            groom_email = wedding.client_email.strip().lower() if is_groom_client and wedding.client_email else ""
            groom_phone = wedding.client_phone.strip() if is_groom_client and wedding.client_phone else ""

            groom_client, _ = Client.objects.get_or_create(
                company_id=wedding.company_id,
                name=groom_name,
                defaults={
                    "cpf": groom_cpf,
                    "email": groom_email,
                    "phone": groom_phone,
                },
            )
            WeddingClient.objects.get_or_create(
                company_id=wedding.company_id,
                wedding_id=wedding.id,
                client_id=groom_client.id,
                role="GROOM",
                defaults={
                    "is_primary_signatory": bool(is_groom_client),
                },
            )

        client_name = wedding.client_name.strip() if wedding.client_name else ""
        if client_name and client_name not in (bride_name, groom_name):
            role_map = {
                "NOIVA": "BRIDE",
                "NOIVO": "GROOM",
                "FINANCIAL_PAYER": "FINANCIAL_PAYER",
                "LEGAL_REPRESENTATIVE": "LEGAL_REPRESENTATIVE",
                "OTHER": "OTHER",
            }
            assigned_role = role_map.get(wedding.client_role, "FINANCIAL_PAYER")
            payer_client, _ = Client.objects.get_or_create(
                company_id=wedding.company_id,
                name=client_name,
                defaults={
                    "cpf": wedding.client_cpf.strip() if wedding.client_cpf else "",
                    "email": wedding.client_email.strip().lower() if wedding.client_email else "",
                    "phone": wedding.client_phone.strip() if wedding.client_phone else "",
                },
            )
            WeddingClient.objects.get_or_create(
                company_id=wedding.company_id,
                wedding_id=wedding.id,
                client_id=payer_client.id,
                role=assigned_role,
                defaults={
                    "is_primary_signatory": True,
                },
            )


def unpopulate_wedding_participants(apps, schema_editor):
    """Reverte os participantes criados na migração de dados."""
    WeddingClient = apps.get_model("weddings", "WeddingClient")
    WeddingClient.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('tenants', '0001_initial'),
        ('weddings', '0004_wedding_client_cpf_wedding_client_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeddingClient',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('BRIDE', 'Noiva'), ('GROOM', 'Noivo'), ('FINANCIAL_PAYER', 'Contratante Financeiro'), ('LEGAL_REPRESENTATIVE', 'Representante Legal'), ('OTHER', 'Outro Envolvido')], default='BRIDE', max_length=30, verbose_name='Papel no Casamento')),
                ('is_primary_signatory', models.BooleanField(default=False, verbose_name='Assina o Contrato?')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Observações')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wedding_roles', to='clients.client', verbose_name='Cliente')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='tenants.company', verbose_name='Empresa')),
                ('wedding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='weddings.wedding', verbose_name='Casamento')),
            ],
            options={
                'verbose_name': 'Participante do Casamento',
                'verbose_name_plural': 'Participantes do Casamento',
                'db_table': 'wedding_participants',
                'indexes': [
                    models.Index(fields=['company', 'wedding'], name='wedding_par_company_279ec1_idx'),
                    models.Index(fields=['wedding', 'role'], name='wedding_par_wedding_0bee75_idx'),
                    models.Index(fields=['client'], name='wedding_par_client__90e2f4_idx'),
                ],
                'unique_together': {('wedding', 'client', 'role')},
            },
        ),
        migrations.RunPython(
            populate_wedding_participants,
            unpopulate_wedding_participants,
        ),
    ]
