# Generated by Django 6.1 on 2026-09-24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_migrate_contract_data'),
        ('weddings', '0005_weddingclient_and_data_migration'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='plannercontract',
            name='weddings_pl_company_4b67ac_idx',
        ),
        migrations.RemoveIndex(
            model_name='plannercontract',
            name='weddings_pl_wedding_612423_idx',
        ),
        migrations.DeleteModel(
            name='PlannerContract',
        ),
    ]
