# Generated by Django 6.1 on 2026-09-26 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weddings', '0006_remove_plannercontract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wedding',
            name='client_role',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Papel do Contratante'),
        ),
        migrations.AlterField(
            model_name='wedding',
            name='status',
            field=models.CharField(choices=[('PROPOSAL', 'Proposta'), ('PLANNING', 'Planejamento'), ('IN_PROGRESS', 'Em Andamento'), ('COMPLETED', 'Concluído'), ('CANCELED', 'Cancelado')], default='IN_PROGRESS', max_length=20),
        ),
    ]
