# Generated by Django 6.1 on 2026-09-27 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weddings', '0007_add_planning_status_and_relax_flat_client_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wedding',
            name='client_role',
            field=models.CharField(blank=True, default='NOIVO', max_length=50, verbose_name='Papel do Contratante'),
        ),
    ]
