# Generated by Django 5.2.9 on 2026-02-01 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Rascunho'), ('PENDING', 'Pendente'), ('SIGNED', 'Assinado'), ('CANCELED', 'Cancelado')], default='DRAFT', max_length=20)),
                ('expiration_date', models.DateField(blank=True, help_text='Data de expiração do contrato', null=True, verbose_name='Data de Vencimento')),
                ('alert_days_before', models.PositiveIntegerField(default=30, help_text='Quantos dias antes do vencimento enviar alerta', verbose_name='Alertar Dias Antes')),
                ('planner_signed_at', models.DateTimeField(blank=True, null=True)),
                ('supplier_signed_at', models.DateTimeField(blank=True, null=True)),
                ('couple_signed_at', models.DateTimeField(blank=True, null=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='contracts/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contrato',
                'verbose_name_plural': 'Contratos',
                'ordering': ['-created_at'],
            },
        ),
    ]
