# Generated by Django 6.1 on 2026-09-24

import uuid
import apps.core.validators
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('logistics', '0014_rename_item_to_supplyitem_and_more'),
        ('tenants', '0001_initial'),
        ('weddings', '0005_weddingclient_and_data_migration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contract_type', models.CharField(choices=[('PLANNER', 'Assessoria'), ('SUPPLIER', 'Fornecedor')], default='SUPPLIER', max_length=20, verbose_name='Tipo de Contrato')),
                ('service_tier', models.CharField(blank=True, choices=[('COMPLETA', 'Assessoria Completa'), ('PARCIAL', 'Assessoria Parcial'), ('FINAL', 'Assessoria do Dia/Final')], max_length=50, null=True, verbose_name='Tipo de Assessoria')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('description', models.TextField(blank=True, default='', verbose_name='Descrição do Contrato')),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Valor nominal de face que consta no documento formalizado', max_digits=10, verbose_name='Valor Total do Contrato')),
                ('installments_count', models.PositiveIntegerField(default=1, verbose_name='Número de Parcelas')),
                ('status', models.CharField(choices=[('DRAFT', 'Rascunho'), ('PENDING', 'Pendente'), ('SIGNED', 'Assinado'), ('CANCELED', 'Cancelado')], default='DRAFT', max_length=20, verbose_name='Status do Contrato')),
                ('expiration_date', models.DateField(blank=True, null=True, verbose_name='Data de Vencimento/Validade')),
                ('alert_days_before', models.PositiveIntegerField(default=30, verbose_name='Dias de Alerta Prévio')),
                ('signed_date', models.DateField(blank=True, help_text='Data em que o contrato foi formalizado externamente', null=True, verbose_name='Data da Assinatura')),
                ('pdf_file', models.FileField(blank=True, help_text='Formatos aceitos: PDF, PNG, JPEG. Tamanho máximo: 10MB.', null=True, upload_to='contracts/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'png', 'jpg', 'jpeg'], message='Tipo de arquivo não suportado. Use PDF, PNG ou JPEG.'), apps.core.validators.MaxFileSizeValidator(max_size=10485760)], verbose_name='Arquivo PDF')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to='clients.client', verbose_name='Contratante Principal')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='tenants.company', verbose_name='Empresa')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='logistics.supplier', verbose_name='Fornecedor')),
                ('wedding', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='weddings.wedding', verbose_name='Casamento')),
            ],
            options={
                'verbose_name': 'Contrato',
                'verbose_name_plural': 'Contratos',
                'db_table': 'contracts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContractAddendum',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor do Aditivo')),
                ('signed_date', models.DateField(blank=True, null=True, verbose_name='Data da Assinatura')),
                ('justification', models.TextField(verbose_name='Justificativa do Aditivo')),
                ('pdf_file', models.FileField(blank=True, help_text='Formatos aceitos: PDF, PNG, JPEG. Tamanho máximo: 10MB.', null=True, upload_to='contracts/addendums/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'png', 'jpg', 'jpeg'], message='Tipo de arquivo não suportado. Use PDF, PNG ou JPEG.'), apps.core.validators.MaxFileSizeValidator(max_size=10485760)], verbose_name='Arquivo PDF do Aditivo')),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('SIGNED', 'Assinado'), ('CANCELED', 'Cancelado')], default='PENDING', max_length=20)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='tenants.company', verbose_name='Empresa')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addendums', to='contracts.contract', verbose_name='Contrato Principal')),
                ('wedding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='weddings.wedding')),
            ],
            options={
                'verbose_name': 'Termo Aditivo',
                'verbose_name_plural': 'Termos Aditivos',
                'db_table': 'contract_addendums',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['company', 'wedding'], name='contracts_company_7cc68b_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['company', 'contract_type'], name='contracts_company_058557_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['status'], name='contracts_status_093df1_idx'),
        ),
        migrations.AddIndex(
            model_name='contractaddendum',
            index=models.Index(fields=['company', 'wedding'], name='contract_ad_company_781866_idx'),
        ),
        migrations.AddIndex(
            model_name='contractaddendum',
            index=models.Index(fields=['contract'], name='contract_ad_contrac_9669b1_idx'),
        ),
        migrations.AddIndex(
            model_name='contractaddendum',
            index=models.Index(fields=['status'], name='contract_ad_status_9c3daf_idx'),
        ),
    ]
