# Generated by Django 6.1 on 2026-09-24

from django.db import migrations


def migrate_existing_contracts_and_planner_contracts(apps, schema_editor):
    """
    Migra dados existentes de logistics_contract, logistics_contractaddendum e
    weddings_plannercontract para as novas tabelas de contracts.
    """
    NewContract = apps.get_model('contracts', 'Contract')
    NewAddendum = apps.get_model('contracts', 'ContractAddendum')

    # 1. Migração de logistics_contract -> contracts (SUPPLIER)
    try:
        LegacyContract = apps.get_model('logistics', 'Contract')
        supplier_contracts = [
            NewContract(
                id=legacy.id,
                uuid=legacy.uuid,
                created_at=legacy.created_at,
                updated_at=legacy.updated_at,
                company_id=legacy.company_id,
                wedding_id=legacy.wedding_id,
                contract_type='SUPPLIER',
                service_tier=None,
                supplier_id=legacy.supplier_id,
                client_id=None,
                name=legacy.name,
                description=legacy.description or '',
                total_amount=legacy.total_amount,
                installments_count=1,
                status=legacy.status,
                expiration_date=legacy.expiration_date,
                alert_days_before=legacy.alert_days_before,
                signed_date=legacy.signed_date,
                pdf_file=legacy.pdf_file,
            )
            for legacy in LegacyContract.objects.all()
        ]
        if supplier_contracts:
            NewContract.objects.bulk_create(supplier_contracts)
    except (LookupError, AttributeError):
        pass

    # 2. Migração de logistics_contractaddendum -> contract_addendums
    try:
        LegacyAddendum = apps.get_model('logistics', 'ContractAddendum')
        addendums = [
            NewAddendum(
                id=legacy.id,
                uuid=legacy.uuid,
                created_at=legacy.created_at,
                updated_at=legacy.updated_at,
                company_id=legacy.company_id,
                wedding_id=legacy.wedding_id,
                contract_id=legacy.contract_id,
                amount=legacy.amount,
                signed_date=legacy.signed_date,
                justification=legacy.justification,
                pdf_file=legacy.pdf_file,
                status=legacy.status,
            )
            for legacy in LegacyAddendum.objects.all()
        ]
        if addendums:
            NewAddendum.objects.bulk_create(addendums)
    except (LookupError, AttributeError):
        pass

    # 3. Migração de weddings_plannercontract -> contracts (PLANNER)
    try:
        LegacyPlannerContract = apps.get_model('weddings', 'Contract')
        try:
            Expense = apps.get_model('finances', 'Expense')
        except LookupError:
            Expense = None

        for legacy in LegacyPlannerContract.objects.all():
            new_contract = NewContract.objects.create(
                uuid=legacy.uuid,
                created_at=legacy.created_at,
                updated_at=legacy.updated_at,
                company_id=legacy.company_id,
                wedding_id=legacy.wedding_id,
                contract_type='PLANNER',
                service_tier=legacy.service_tier,
                supplier_id=None,
                client_id=None,
                name=f"Contrato de Assessoria ({legacy.service_tier})",
                description="Contrato de honorários da assessoria cerimonial",
                total_amount=legacy.effective_amount,
                installments_count=legacy.installments_count,
                status=legacy.status,
                expiration_date=None,
                alert_days_before=30,
                signed_date=legacy.signed_date,
                pdf_file=legacy.pdf_file,
            )

            # Vincula despesas de honorários previamente criadas sem contract_id
            if Expense is not None:
                Expense.objects.filter(
                    wedding_id=legacy.wedding_id,
                    contract__isnull=True,
                    name__icontains='Honorários',
                ).update(contract=new_contract)
    except (LookupError, AttributeError):
        pass

    # 4. Ajuste de sequências numéricas no PostgreSQL se aplicável
    if schema_editor.connection.vendor == "postgresql":
        with schema_editor.connection.cursor() as cursor:
            cursor.execute(
                """
                SELECT setval(pg_get_serial_sequence('contracts', 'id'), coalesce(max(id), 1), max(id) IS NOT NULL) FROM contracts;
                SELECT setval(pg_get_serial_sequence('contract_addendums', 'id'), coalesce(max(id), 1), max(id) IS NOT NULL) FROM contract_addendums;
                """
            )


def reverse_migration(apps, schema_editor):
    """Reversão intencionalmente nula.

    A cópia logistics/weddings -> contracts é irreversível por design:
    os modelos legados são deletados em `logistics.0015` e `weddings.0006`,
    e os PLANNER recebem IDs novos. Reverter exige restore de backup
    pré-migração. Ver auditoria complementar em `0003`.
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
        ('logistics', '0014_rename_item_to_supplyitem_and_more'),
        ('weddings', '0005_weddingclient_and_data_migration'),
    ]

    operations = [
        migrations.RunPython(
            migrate_existing_contracts_and_planner_contracts,
            reverse_code=reverse_migration,
        ),
    ]
