# Generated by Django 5.2.9 on 2026-02-01 21:22

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Installment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installment_number', models.PositiveIntegerField(help_text='Ex: 1, 2, 3...', verbose_name='Número da Parcela')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Valor da Parcela')),
                ('due_date', models.DateField(verbose_name='Data de Vencimento')),
                ('paid_date', models.DateField(blank=True, null=True, verbose_name='Data de Pagamento')),
                ('status', models.CharField(choices=[('PAID', 'Pago'), ('PENDING', 'Pendente'), ('OVERDUE', 'Atrasado')], default='PENDING', max_length=10, verbose_name='Status')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Parcela',
                'verbose_name_plural': 'Parcelas',
                'ordering': ['due_date', 'installment_number'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Quantidade física necessária', verbose_name='Quantidade')),
                ('acquisition_status', models.CharField(choices=[('PENDING', 'Pendente'), ('IN_PROGRESS', 'Em Andamento'), ('DONE', 'Concluído')], default='PENDING', help_text='Status da logística/contratação', max_length=20, verbose_name='Status de Aquisição')),
                ('estimated_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Valor estimado/orçado', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Custo Estimado')),
                ('actual_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Valor final após negociação', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Custo Real')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Itens',
                'ordering': ['-created_at'],
            },
        ),
    ]
