# Generated by Django 5.2.9 on 2026-02-02 01:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('items', '0001_initial'),
        ('suppliers', '0001_initial'),
        ('weddings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='budget_category',
            field=models.ForeignKey(help_text='Categoria do item (financeiro + logístico)', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='weddings.budgetcategory', verbose_name='Categoria'),
        ),
        migrations.AddField(
            model_name='item',
            name='supplier',
            field=models.ForeignKey(blank=True, help_text='Fornecedor responsável pelo item/serviço', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='suppliers.supplier', verbose_name='Fornecedor'),
        ),
        migrations.AddField(
            model_name='item',
            name='wedding',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='weddings.wedding', verbose_name='Casamento'),
        ),
        migrations.AddField(
            model_name='installment',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='items.item', verbose_name='Item'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['wedding', 'budget_category'], name='items_item_wedding_ddad4f_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['wedding', 'acquisition_status'], name='items_item_wedding_a20a91_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['budget_category'], name='items_item_budget__394587_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['-created_at'], name='items_item_created_3eaa9f_idx'),
        ),
        migrations.AddIndex(
            model_name='installment',
            index=models.Index(fields=['status', 'due_date'], name='items_insta_status_388176_idx'),
        ),
        migrations.AddIndex(
            model_name='installment',
            index=models.Index(fields=['due_date'], name='items_insta_due_dat_a54c6b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='installment',
            unique_together={('item', 'installment_number')},
        ),
    ]
