# Generated by Django 5.2.4 on 2025-07-24 05:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("budget", "0001_initial"),
        ("weddings", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="budget",
            name="wedding",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="budget",
                to="weddings.wedding",
            ),
        ),
    ]
