# Generated by Django 5.2.3 on 2025-07-17 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
        ('weddings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='wedding',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='budget', to='weddings.wedding'),
        ),
    ]
