# Generated by Django 5.2.4 on 2025-07-24 23:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budget", "0002_initial"),
        ("weddings", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="budget",
            name="wedding",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="budget",
                to="weddings.wedding",
            ),
            preserve_default=False,
        ),
    ]
